Repository transformstudios/statamic-review, pull requests merged in 2025-03, with the labels that each got.

#54 Parent might be an empty Entry
  src/Fieldtypes/Review.php
Labels: fix

#53 Laravel 12.x Compatibility
  composer.json
Labels: feature

#56 Attempt to fix action
  .github/workflows/create-draft-release.yml
Labels: chore
